---
# tasks file for vector-role
- name: Download Vector RPM
  ansible.builtin.get_url:
    url: "{{ vector_rpm_url }}"
    dest: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
    mode: '0644'

- name: Install Vector RPM
  become: true
  ansible.builtin.yum:
    name: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present

- name: Deploy Vector Configuration
  become: true
  ansible.builtin.template:
    src: "{{ vector_config_template }}"
    dest: "{{ vector_config_destination }}"
    mode: '0644'
